# Generated by Django 4.2.4 on 2023-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_slug_alter_job_posted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
